# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Source\LIME\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(18, 18))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.originBox = QtWidgets.QGroupBox(self.centralwidget)
        self.originBox.setEnabled(True)
        self.originBox.setObjectName("originBox")
        self.horizontalLayout_5.addWidget(self.originBox)
        self.enhancedBox = QtWidgets.QGroupBox(self.centralwidget)
        self.enhancedBox.setObjectName("enhancedBox")
        self.horizontalLayout_5.addWidget(self.enhancedBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.smoothnessSlider = QtWidgets.QSlider(self.groupBox)
        self.smoothnessSlider.setEnabled(True)
        self.smoothnessSlider.setMinimum(1)
        self.smoothnessSlider.setMaximum(400)
        self.smoothnessSlider.setProperty("value", 301)
        self.smoothnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.smoothnessSlider.setObjectName("smoothnessSlider")
        self.horizontalLayout_3.addWidget(self.smoothnessSlider)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.brightnessSlider = QtWidgets.QSlider(self.groupBox)
        self.brightnessSlider.setMinimum(1)
        self.brightnessSlider.setMaximum(100)
        self.brightnessSlider.setSingleStep(1)
        self.brightnessSlider.setPageStep(10)
        self.brightnessSlider.setProperty("value", 70)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.horizontalLayout_3.addWidget(self.brightnessSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 700, 18))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.recentOpenMenu = QtWidgets.QMenu(self.menu)
        self.recentOpenMenu.setObjectName("recentOpenMenu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_6 = QtWidgets.QMenu(self.menu_4)
        self.menu_6.setObjectName("menu_6")
        self.menu_8 = QtWidgets.QMenu(self.menuBar)
        self.menu_8.setObjectName("menu_8")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.openAct = QtWidgets.QAction(MainWindow)
        self.openAct.setObjectName("openAct")
        self.aboutAct = QtWidgets.QAction(MainWindow)
        self.aboutAct.setObjectName("aboutAct")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.undoAct = QtWidgets.QAction(MainWindow)
        self.undoAct.setObjectName("undoAct")
        self.redoAct = QtWidgets.QAction(MainWindow)
        self.redoAct.setObjectName("redoAct")
        self.enhanceAct = QtWidgets.QAction(MainWindow)
        self.enhanceAct.setObjectName("enhanceAct")
        self.saveAct = QtWidgets.QAction(MainWindow)
        self.saveAct.setObjectName("saveAct")
        self.printAct = QtWidgets.QAction(MainWindow)
        self.printAct.setObjectName("printAct")
        self.clearAct = QtWidgets.QAction(MainWindow)
        self.clearAct.setObjectName("clearAct")
        self.quitAct = QtWidgets.QAction(MainWindow)
        self.quitAct.setObjectName("quitAct")
        self.copyAct = QtWidgets.QAction(MainWindow)
        self.copyAct.setObjectName("copyAct")
        self.illuMapAct = QtWidgets.QAction(MainWindow)
        self.illuMapAct.setObjectName("illuMapAct")
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_21 = QtWidgets.QAction(MainWindow)
        self.action_21.setObjectName("action_21")
        self.action_22 = QtWidgets.QAction(MainWindow)
        self.action_22.setObjectName("action_22")
        self.action_23 = QtWidgets.QAction(MainWindow)
        self.action_23.setObjectName("action_23")
        self.thankAct = QtWidgets.QAction(MainWindow)
        self.thankAct.setObjectName("thankAct")
        self.saveAsAct = QtWidgets.QAction(MainWindow)
        self.saveAsAct.setObjectName("saveAsAct")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.histAct = QtWidgets.QAction(MainWindow)
        self.histAct.setObjectName("histAct")
        self.gammaAct = QtWidgets.QAction(MainWindow)
        self.gammaAct.setObjectName("gammaAct")
        self.menu.addAction(self.openAct)
        self.menu.addAction(self.recentOpenMenu.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.saveAct)
        self.menu.addAction(self.saveAsAct)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.printAct)
        self.menu.addSeparator()
        self.menu.addAction(self.clearAct)
        self.menu.addSeparator()
        self.menu.addAction(self.quitAct)
        self.menu_2.addAction(self.action)
        self.menu_3.addAction(self.aboutAct)
        self.menu_3.addAction(self.thankAct)
        self.menu_5.addAction(self.undoAct)
        self.menu_5.addAction(self.redoAct)
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.copyAct)
        self.menu_6.addAction(self.action_1)
        self.menu_6.addAction(self.action_21)
        self.menu_4.addAction(self.enhanceAct)
        self.menu_4.addAction(self.illuMapAct)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.histAct)
        self.menu_4.addAction(self.gammaAct)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.menu_6.menuAction())
        self.menu_8.addAction(self.action_22)
        self.menu_8.addAction(self.action_23)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_8.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.openAct)
        self.toolBar.addAction(self.enhanceAct)
        self.toolBar.addAction(self.clearAct)
        self.toolBar.addAction(self.saveAct)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "低光照图像增强系统"))
        self.originBox.setTitle(_translate("MainWindow", "原始图片"))
        self.enhancedBox.setTitle(_translate("MainWindow", "增强后图片"))
        self.label.setText(_translate("MainWindow", "平滑度"))
        self.label_2.setText(_translate("MainWindow", "亮度"))
        self.label_3.setText(_translate("MainWindow", "<a href=\"https://github.com/aeinrw/LIME\"><img src=\"data/github.png\"></a>"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.recentOpenMenu.setTitle(_translate("MainWindow", "最近打开"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.menu_5.setTitle(_translate("MainWindow", "编辑"))
        self.menu_4.setTitle(_translate("MainWindow", "增强"))
        self.menu_6.setTitle(_translate("MainWindow", "降噪"))
        self.menu_8.setTitle(_translate("MainWindow", "视图"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.openAct.setText(_translate("MainWindow", "打开"))
        self.aboutAct.setText(_translate("MainWindow", "关于"))
        self.action.setText(_translate("MainWindow", "参数调整"))
        self.undoAct.setText(_translate("MainWindow", "撤销"))
        self.redoAct.setText(_translate("MainWindow", "重做"))
        self.enhanceAct.setText(_translate("MainWindow", "增强"))
        self.enhanceAct.setToolTip(_translate("MainWindow", "低光照增强"))
        self.saveAct.setText(_translate("MainWindow", "保存"))
        self.printAct.setText(_translate("MainWindow", "打印"))
        self.clearAct.setText(_translate("MainWindow", "清空"))
        self.quitAct.setText(_translate("MainWindow", "退出"))
        self.copyAct.setText(_translate("MainWindow", "复制图片"))
        self.illuMapAct.setText(_translate("MainWindow", "显示光照图"))
        self.action_1.setText(_translate("MainWindow", "降噪1"))
        self.action_21.setText(_translate("MainWindow", "降噪2"))
        self.action_22.setText(_translate("MainWindow", "菜单栏"))
        self.action_23.setText(_translate("MainWindow", "进度条"))
        self.thankAct.setText(_translate("MainWindow", "致谢"))
        self.saveAsAct.setText(_translate("MainWindow", "保存为"))
        self.action_2.setText(_translate("MainWindow", "保存光照图"))
        self.histAct.setText(_translate("MainWindow", "直方图均衡"))
        self.gammaAct.setText(_translate("MainWindow", "Gamma变换"))
