# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Source\LIME\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(18, 18))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.originBox = QtWidgets.QGroupBox(self.centralwidget)
        self.originBox.setEnabled(True)
        self.originBox.setObjectName("originBox")
        self.horizontalLayout_5.addWidget(self.originBox)
        self.enhancedBox = QtWidgets.QGroupBox(self.centralwidget)
        self.enhancedBox.setObjectName("enhancedBox")
        self.horizontalLayout_5.addWidget(self.enhancedBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 700, 18))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.recentOpenMenu = QtWidgets.QMenu(self.menu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/image/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recentOpenMenu.setIcon(icon1)
        self.recentOpenMenu.setObjectName("recentOpenMenu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_8 = QtWidgets.QMenu(self.menuBar)
        self.menu_8.setObjectName("menu_8")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.openAct = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resource/image/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAct.setIcon(icon2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.openAct.setFont(font)
        self.openAct.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.openAct.setIconVisibleInMenu(True)
        self.openAct.setObjectName("openAct")
        self.aboutAct = QtWidgets.QAction(MainWindow)
        self.aboutAct.setIcon(icon)
        self.aboutAct.setObjectName("aboutAct")
        self.settingAct = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resource/image/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingAct.setIcon(icon3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.settingAct.setFont(font)
        self.settingAct.setObjectName("settingAct")
        self.undoAct = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resource/image/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoAct.setIcon(icon4)
        self.undoAct.setObjectName("undoAct")
        self.redoAct = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resource/image/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redoAct.setIcon(icon5)
        self.redoAct.setObjectName("redoAct")
        self.enhanceAct = QtWidgets.QAction(MainWindow)
        self.enhanceAct.setCheckable(False)
        self.enhanceAct.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resource/image/enhence.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enhanceAct.setIcon(icon6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.enhanceAct.setFont(font)
        self.enhanceAct.setObjectName("enhanceAct")
        self.saveAct = QtWidgets.QAction(MainWindow)
        self.saveAct.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resource/image/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAct.setIcon(icon7)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saveAct.setFont(font)
        self.saveAct.setObjectName("saveAct")
        self.printAct = QtWidgets.QAction(MainWindow)
        self.printAct.setEnabled(False)
        self.printAct.setObjectName("printAct")
        self.clearAct = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resource/image/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearAct.setIcon(icon8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.clearAct.setFont(font)
        self.clearAct.setObjectName("clearAct")
        self.quitAct = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resource/image/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAct.setIcon(icon9)
        self.quitAct.setObjectName("quitAct")
        self.copyAct = QtWidgets.QAction(MainWindow)
        self.copyAct.setObjectName("copyAct")
        self.illuMapAct = QtWidgets.QAction(MainWindow)
        self.illuMapAct.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resource/image/1211052.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.illuMapAct.setIcon(icon10)
        self.illuMapAct.setObjectName("illuMapAct")
        self.denoiseAct = QtWidgets.QAction(MainWindow)
        self.denoiseAct.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("resource/image/denoise.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.denoiseAct.setIcon(icon11)
        self.denoiseAct.setObjectName("denoiseAct")
        self.showToolBarAct = QtWidgets.QAction(MainWindow)
        self.showToolBarAct.setCheckable(True)
        self.showToolBarAct.setObjectName("showToolBarAct")
        self.showProgressBarAct = QtWidgets.QAction(MainWindow)
        self.showProgressBarAct.setCheckable(True)
        self.showProgressBarAct.setObjectName("showProgressBarAct")
        self.thankAct = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("resource/image/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.thankAct.setIcon(icon12)
        self.thankAct.setObjectName("thankAct")
        self.saveAsAct = QtWidgets.QAction(MainWindow)
        self.saveAsAct.setEnabled(False)
        self.saveAsAct.setIcon(icon7)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saveAsAct.setFont(font)
        self.saveAsAct.setObjectName("saveAsAct")
        self.saveIlluMapAct = QtWidgets.QAction(MainWindow)
        self.saveIlluMapAct.setEnabled(False)
        self.saveIlluMapAct.setIcon(icon7)
        self.saveIlluMapAct.setObjectName("saveIlluMapAct")
        self.menu.addAction(self.openAct)
        self.menu.addAction(self.recentOpenMenu.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.saveAct)
        self.menu.addAction(self.saveAsAct)
        self.menu.addAction(self.saveIlluMapAct)
        self.menu.addSeparator()
        self.menu.addAction(self.clearAct)
        self.menu.addSeparator()
        self.menu.addAction(self.quitAct)
        self.menu_2.addAction(self.settingAct)
        self.menu_3.addAction(self.aboutAct)
        self.menu_3.addAction(self.thankAct)
        self.menu_4.addAction(self.enhanceAct)
        self.menu_4.addAction(self.illuMapAct)
        self.menu_4.addSeparator()
        self.menu_8.addAction(self.showToolBarAct)
        self.menu_8.addAction(self.showProgressBarAct)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_8.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.openAct)
        self.toolBar.addAction(self.enhanceAct)
        self.toolBar.addAction(self.denoiseAct)
        self.toolBar.addAction(self.clearAct)
        self.toolBar.addAction(self.saveAsAct)
        self.toolBar.addAction(self.settingAct)

        self.retranslateUi(MainWindow)
        self.showToolBarAct.triggered['bool'].connect(self.toolBar.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "低光照图像增强系统"))
        self.originBox.setTitle(_translate("MainWindow", "原始图片"))
        self.enhancedBox.setTitle(_translate("MainWindow", "增强后图片"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.recentOpenMenu.setTitle(_translate("MainWindow", "最近打开"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.menu_4.setTitle(_translate("MainWindow", "增强"))
        self.menu_8.setTitle(_translate("MainWindow", "视图"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.openAct.setText(_translate("MainWindow", "打开"))
        self.aboutAct.setText(_translate("MainWindow", "关于"))
        self.settingAct.setText(_translate("MainWindow", "参数"))
        self.undoAct.setText(_translate("MainWindow", "撤销"))
        self.redoAct.setText(_translate("MainWindow", "重做"))
        self.enhanceAct.setText(_translate("MainWindow", "增强"))
        self.enhanceAct.setToolTip(_translate("MainWindow", "低光照增强"))
        self.saveAct.setText(_translate("MainWindow", "保存"))
        self.printAct.setText(_translate("MainWindow", "打印"))
        self.clearAct.setText(_translate("MainWindow", "清空"))
        self.quitAct.setText(_translate("MainWindow", "退出"))
        self.copyAct.setText(_translate("MainWindow", "复制"))
        self.illuMapAct.setText(_translate("MainWindow", "光照图"))
        self.denoiseAct.setText(_translate("MainWindow", "降噪"))
        self.showToolBarAct.setText(_translate("MainWindow", "工具栏"))
        self.showToolBarAct.setToolTip(_translate("MainWindow", "工具栏"))
        self.showProgressBarAct.setText(_translate("MainWindow", "进度条"))
        self.thankAct.setText(_translate("MainWindow", "致谢"))
        self.saveAsAct.setText(_translate("MainWindow", "另存为"))
        self.saveIlluMapAct.setText(_translate("MainWindow", "保存光照图"))
